### ISSUE TITLE
How to make it work in Expo app?

### ISSUE THREAD

**Issue by hassantauqeer** [coreyphillips/rn-bitcoinjs-lib#2]
How to make it work in Expo app? Please Help!

**Comment by hassantauqeer** [comment]
While trying to resolve module `crypto`  module field that could not be resolved

**Comment by coreyphillips** [comment]
Based on what you mentioned it's possible that you skipped the following step in the README: ```Add/Uncomment "require('crypto')" at the bottom of shim.js```

If you didn't skip the step above it's possible that this library will not work with an Expo app and would most likely need to be ejected from Expo to get it working.
