### ISSUE TITLE
undefined is not an object (evaluating RNRandomBytes.seed)

### ISSUE THREAD

**Issue by maguayo** [coreyphillips/rn-bitcoinjs-lib#4]
I've followed the README but the app does not load. I get this error, any ideas why?
```
undefined is not an object (evaluating RNRandomBytes.seed)
```

Thanks

**Comment by coreyphillips** [comment]
Hey @maguayo. There are a few things that could be causing this so I'll add each item as a bullet below:
- It's possible that `react-native-randombytes` isn't properly linked. To resolve this try running the `react-native link react-native-randombytes` command again and then try restarting your project.
- Ensure that you're importing shim.js like so, (`import "./shim";`) into the file you're calling from.
- Lastly, ensure you've made the appropriate changes to the shim.js file detailed in the setup instructions. Feel free to use this [shim.js file](https://github.com/coreyphillips/RNBitcoinJS/blob/master/shim.js) as a reference to match up with your own.

I've created a standalone project that you can use as a reference to ensure that you've set everything up correctly. You can find that [here.](https://github.com/coreyphillips/RNBitcoinJS)

Hope this helps. If not, please let me know so we can keep troubleshooting.

**Comment by maguayo** [comment]
Solved thanks
